routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('posts', 'PostController')->only(['index'])->names('posts');

Route::resource('parser', 'ParserController')->only(['index', 'store'])->names('parser');

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Author extends Model
{
    use SoftDeletes;

    /**
     * Post to author
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    /**
     * @var array attributes for mass-assignment
     */
    protected $fillable = [
        'author_id',
        'url_id',
        'title',
        'slug',
        'content',
        'keywords',
        'published_at',
    ];

    /**
     * Author to post
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function author()
    {
        return $this->belongsTo(Author::class);
    }

    /**
     * URL to post
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function url()
    {
        return $this->belongsTo(Url::class);
    }
}

app/Models/Url.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Url extends Model
{
    use SoftDeletes;

    /**
     * Post to URL
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ParserController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\ParsingUrl;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ParserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        return view('parser');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function store(Request $request)
    {
        $parsing_url = new ParsingUrl();
        $parsing_url->parse_data($request->url);

        return redirect()->route('posts.index');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\PostRepositories;
use Illuminate\Contracts\View\Factory;
use Illuminate\View\View;

class PostController extends Controller
{
    /**
     * @var PostRepositories
     */
    private $post_repositories;

    /**
     * PostController constructor.
     */
    public function __construct()
    {
        $this->post_repositories = app(PostRepositories::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     * @throws \Exception
     */
    public function index()
    {
        $post_paginator = $this->post_repositories->getPostsForTable();

        return view('posts', compact('post_paginator'));
    }
}

resources/views/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{{ asset('css/mdb.min.css') }}">
    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

    <link href="{{ asset('css/addons/datatables.min.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                Test task
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="{{ Request::path() === '/parser' ? 'nav-link active' : 'nav-link'}}"
                           href="{{ url('parser') }}">Parser</a>
                    </li>
                    <li class="nav-item">
                        <a class="{{ Request::path() === 'posts' ? 'nav-link active' : 'nav-link'}}"
                           href="{{ url('posts') }}">Posts</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>

<!-- jQuery -->
<script type="text/javascript" src="{{ asset('js/jquery.min.js') }}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{{ asset('js/popper.min.js') }}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{{ asset('js/bootstrap.min.js') }}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{{ asset('js/mdb.min.js') }}"></script>
<!-- MDBootstrap Datatables  -->
<script type="text/javascript" src="{{ asset('js/addons/datatables.min.js') }}"></script>
</body>
</html>

resources/views/parser.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <form method="POST" action="{{ route('parser.store') }}">
            @csrf
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            Needs to parse?
                        </div>
                        <div class="card-body">
                            <div class="card-title"></div>
                            <div class="card-subtitle mb-2 text-muted"></div>
                            <div class="form-group">
                                <label for="url">Parsing URL</label>
                                <input name="url"
                                       value="https://www.segodnya.ua/regions/odessa.html"
                                       id="url"
                                       type="text"
                                       class="form-control"
                                       minlength="3"
                                       required>
                            </div>
                            <button type="submit" class="btn btn-primary">Parse</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/posts.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <table id="dtBasicExample" class="table table-striped table-bordered table-sm"
                               cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th class="th-sm">Published
                                </th>
                                <th class="th-sm">Title
                                </th>
                                <th class="th-sm">Author
                                </th>
                                <th class="th-sm">Keywords
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($post_paginator as $paginator_page)
                                <tr>
                                    <td>{{ date('H:i d.m.Y', strtotime($paginator_page->published_at)) }}</td>
                                    <td>
                                        <a href="{{ $paginator_page->url->url }}"> {{ $paginator_page->title }} </a>
                                    </td>
                                    <td>{{ $paginator_page->author->name }}</td>
                                    <td>{{ $paginator_page->keywords }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="th-sm">Published
                                </th>
                                <th class="th-sm">Title
                                </th>
                                <th class="th-sm">Author
                                </th>
                                <th class="th-sm">Keywords
                                </th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- table option script -->
    <script type="text/javascript" src="{{ asset('js/jquery.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#dtBasicExample').DataTable({
                "order": [[2, "desc"]],
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
@endsection